Sprint 10 - Filmorate project - Review 1 - branch add-friend-likes added
Alexey-Sutyrin/java-sprint9-filmorate pull request #2
Opened 2024-01-18 17:43 UTC by Alexey-Sutyrin

Sprint 10 - Filmorate project - Review 1 - branch add-friend-likes added

2024-01-19 07:21 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>  public class UserController {
Логирование в контроллерах и обработчике ошибок нужно было оставить.

2024-01-19 07:25 UTC, VadimZharkov commented on pom.xml
> +			<groupId>com.google.guava</groupId>
Не нашел где данная зависимость используется, след-но зачем добавлена?

2024-01-19 07:27 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotNull
Чем `@NotNull` для строки лучше `@NotBlank`?

2024-01-19 07:40 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/validator/UserValidator.java
> +    private static void validateLogin(String login) {
Данный метод не понадобится, если на поле login повесить
` @NotBlank(message = "Логин пользователя не может быть пустым")`
Если в методе контроллера используется `@Valid`, то проверится и выпадет эксепшен на момент вызова метода контроллера.
Повторюсь, что два типа валидации без какой-то  крайней необходимости, лучше не смешивать.
Все что можно проверить с помощью аннотаций, лучше с ними и проверить.

2024-01-19 07:43 UTC, VadimZharkov requested changes
Можно улучшить.

2024-01-19 13:24 UTC, Alexey-Sutyrin commented on pom.xml
> +			<groupId>com.google.guava</groupId>
Зависимость  использовалась в UserService.java для 
Sets.intersection, и только там. Согласен, излишество, заменил на стандартное решение getIntersection с использованием HashSet, guava из POM.xml убрал

2024-01-20 13:35 UTC, VadimZharkov requested changes
Логирование в методы контроллеров и обработчик ошибок нужно добавить.
Это требование ТЗ предыдущего спринта. Текущий спринт - продолжение предыдущего. Поэтому функциональность не должна убираться.

2024-01-22 08:55 UTC, VadimZharkov approved these changes

2024-01-22 12:41 UTC, merged