Sprint 11 - Filmorate project - First try - add-database Pull start
Alexey-Sutyrin/java-sprint9-filmorate pull request #4
Opened 2024-01-23 10:22 UTC by Alexey-Sutyrin

Filmorate 11 - Pull request to check

2024-01-24 07:56 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
>  public class ErrorHandler {
Нужно добавить логирование. Требование тянется с пред. спринтов

2024-01-24 07:57 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
Нужно добавить логирование в каждый метод. Требование тянется с пред. спринтов

2024-01-24 08:02 UTC, VadimZharkov reviewed
Нет настроек подключения к БД в application.properties

2024-01-24 08:03 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    private final String name;
Имя жанра может быть null или пустым?

2024-01-24 08:06 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +
Зачем в каждом методе пустые строки? Это не соответствует code style

2024-01-24 08:08 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +    public Map<Long, Film> getFilms() {
Нужно вернуть обычный List т.к. в сущности есть идентификатор

2024-01-24 08:08 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +
Пустая строка?

2024-01-24 08:11 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +                jdbcTemplate.update(queryForFilmGenre, film.getId(), genre.getId());
В цикле вставлять по одной записи не эфективно, лучше воспользоваться пакетной операцией batchUpdate
https://habr.com/ru/articles/703828/

2024-01-24 08:11 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        if (!film.getGenres().isEmpty()) {
Повторяющийся код, лучше вынести в отдельный метод

2024-01-24 08:13 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        List<Genre> genresOfFilm = getGenresOfFilm(film.getId());
В маппере не должно быть доп. обращений к БД

2024-01-24 08:15 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/GenreDbStorage.java
> +    public Map<Integer, Genre> getAllGenres() {
Опять же нет никакого смысла делать мапу, достаточно простого списка

2024-01-24 08:16 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +            User user = User.builder()
Нужно воспользоваться методом маппером, код дублируется с ним

2024-01-24 08:17 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +                "(SELECT F.USER_SECOND_ID FROM FRIENDSHIP AS F WHERE F.USER_FIRST_ID = ?);";
Эфективней через JOIN

2024-01-24 08:19 UTC, VadimZharkov requested changes
Нужно исправить замечания

2024-01-25 06:27 UTC, VadimZharkov approved these changes

2024-01-25 06:54 UTC, Alexey-Sutyrin commented
Sprint 11 branch (add-database ) finally approved.

2024-01-25 06:54 UTC, merged